// add to works folder the rest of the works projects
import Head from "next/head";
import Layout from "../component/layout/article";
import NextLink from "next/link";
import { ChevronRightIcon } from "@chakra-ui/icons";
import Image from "next/image";
import myPhoto from "../images/myphoto.jpg";
import Section from "../component/section";
import Paragraph from "../component/paraghraph";
import { BioSection, BioYear } from "../component/bio";
import { IoLogoGithub, IoLogoLinkedin } from "react-icons/io";
import {
  Container,
  Box,
  Heading,
  useColorModeValue,
  Link,
  Button,
  List,
  ListItem,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <Layout title="Home">
      <Container>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* the main content except the Bio */}
        <Container
          mt={20}
          color={useColorModeValue("gray.800", "whiteAlpha.900")}
        >
          <Box
            fontWeight="bold"
            borderRadius="lg"
            p={3}
            align="center"
            mb={6}
            bg={useColorModeValue("gray.200", "whiteAlpha.200")}
          >
            Hello, I&apos;m a front end developer based in Iraq!
          </Box>

          <Box display={{ md: "flex" }}>
            <Box flexGrow="1">
              <Heading as="h2" variant="page-title">
                Hassan Mohamed
              </Heading>
              <p fontSize="xl">front end Dev.</p>
            </Box>
            <Box
              flexShrink={0}
              mt={{ base: 4, md: 0 }}
              ml={{ md: 6 }}
              align="center"
            >
              <Image
                alt="hassan photo"
                style={{
                  border: "1px white solid",
                  borderRadius: "50%",
                  display: "inline-block",
                  pointerEvents: "none",
                  objectFit: "cover",
                }}
                width={200}
                height={200}
                src={myPhoto}
              />
            </Box>
          </Box>

          {/* work section */}
          <Section delay={0.1}>
            <Heading as="h2" variant="section-title">
              Work
            </Heading>
            <Paragraph>
              Hassan is a freelance and a front end dev working from home I have
              passion for building websites and web apps
              <NextLink href="/works/inkdrop">
                <Link>Inkdrop</Link>
              </NextLink>
            </Paragraph>
            <Box align="center" my={4}>
              <NextLink href={"/works"}>
                <Button
                  colorScheme={"teal"}
                  rightIcon={<ChevronRightIcon mt={1} />}
                >
                  my Portfolio
                </Button>
              </NextLink>
            </Box>
          </Section>
        </Container>

        {/* Bio section */}
        <Section delay={0.2}>
          <Heading as="h3" variant="section-title">
            Bio
          </Heading>
          <BioSection>
            <BioYear>2002</BioYear>
            Born in Basrah, Iraq.
          </BioSection>
          <BioSection>
            <BioYear>2021</BioYear>
            graduation from highschool.
          </BioSection>
          <BioSection>
            <BioYear>2021</BioYear>
            work as a freelancer.
          </BioSection>
        </Section>
        <Section delay={0.4}>
          <BioSection>
            I &#128151;
            <Paragraph>
              video games, reading books, learn new thing, running.
            </Paragraph>
          </BioSection>
        </Section>

        <Section delay={0.4}>
          <Heading as={"h3"} variants="section-title">
            on the web
          </Heading>
          <List display={"flex"} gap={8}>
            <ListItem>
              <Link
                target={"_blank"}
                href="https://www.github.com/william-iq397"
              >
                <Button
                  display={"flex"}
                  alignItems={"center"}
                  gap="10px"
                  colorScheme="teal"
                  variant="ghost"
                >
                  
                  <IoLogoGithub /> Github
                </Button>
              </Link>
            </ListItem>
            <ListItem>
              <Link target={"_blank"} href="#">
                <Button
                  colorScheme="teal"
                  display={"flex"}
                  alignItems={"center"}
                  gap="10px"
                  variant="ghost"
                >
                  
                  <IoLogoLinkedin /> Linkedin
                </Button>
              </Link>
            </ListItem>
          </List>
        </Section>
      </Container>
    </Layout>
  );
}
